---
all:
  children:
    openclaw_vms:
      hosts:
        openclaw-vm:
          ansible_host: 192.168.100.10
          ansible_user: openclaw
          ansible_ssh_private_key_file: ~/.ssh/openclaw_vm
          ansible_python_interpreter: /usr/bin/python3
      vars:
        ansible_connection: ssh
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
