---
# Ansible Galaxy Collections
collections:
  - name: community.general
    version: ">=8.0.0,<12.0.0"
  - name: community.crypto
    version: ">=3.0.0,<4.0.0"
  - name: ansible.posix
    version: ">=1.5.0"

# Ansible Galaxy Roles (if any third-party roles are needed)
roles: []
